import 'dart:convert';

import 'package:currency_converter/shared/main_cubit/main_states.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:http/http.dart' as http;

class MainCubit extends Cubit<MainState> {
  MainCubit() : super(MainInitial());

  static MainCubit get(context) => BlocProvider.of(context);

  List<String> currencies = [
    "DZD",
    "AOA",
    "XOF",
    "BWP",
    "XOF",
    "BIF",
    "CVE",
    "XAF",
    "XAF",
    "XAF",
    "KMF",
    "CDF",
    "XAF",
    "XOF",
    "DJF",
    "EGP",
    "XAF",
    "ERN",
    "SZL",
    "ETB",
    "XAF",
    "GMD",
    "GHS",
    "GNF",
    "XOF",
    "KES",
    "LSL",
    "LRD",
    "LYD",
    "MGA",
    "MWK",
    "XOF",
    "MRO",
    "MUR",
    "MAD",
    "MZN",
    "NAD",
    "XOF",
    "NGN",
    "RWF",
    "STN",
    "XOF",
    "SCR",
    "SLL",
    "SOS",
    "ZAR",
    "ALL",
    "EUR",
    "EUR",
    "BYN",
    "EUR",
    "BAM",
    "BGN",
    "HRK",
    "EUR",
    "CZK",
    "DKK",
    "EUR",
    "DKK",
    "EUR",
    "EUR",
    "EUR",
    "GIP",
    "EUR",
    "GBP",
    "HUF",
    "ISK",
    "EUR",
    "GBP",
    "EUR",
    "GBP",
    "EUR",
    "EUR",
    "CHF",
    "EUR",
    "EUR",
    "EUR",
    "MDL",
    "EUR",
    "EUR",
    "EUR",
    "MKD",
    "NOK",
    "PLN",
    "EUR",
    "RON",
    "RUB",
    "EUR",
    "RSD",
    "EUR",
    "EUR",
    "EUR",
    "NOK",
    "SEK",
    "CHF",
    "CAD",
    "USD",
    "MXN",
    "DKK",
    "CUP",
    "DOP",
    "CRC",
    "JMD",
    "PAB",
    "HNL",
    "HTG",
    "USD",
    "NIO",
    "BSD",
    "TTD",
    "GTQ",
    "BBD",
    "XCD",
    "XCD",
    "XCD",
    "XCD",
    "XCD",
    "BZD",
    "XCD",
    "EUR",
    "XCD",
    "USD",
    "USD",
    "XCD",
    "KYD",
    "AWG",
    "BMD",
    "USD",
    "USD",
    "ANG",
    "EUR",
    "EUR",
    "USD",
    "USD",
    "USD",
    "EUR",
    'ARS',
    'BOB',
    'BRL',
    'CLP',
    'COP',
    'USD',
    'GYD',
    'PYG',
    'PEN',
    'SRD',
    'UYU',
    'VES',
    'AFN',
    'AMD',
    'AZN',
    'BHD',
    'BDT',
    'BTN',
    'BND',
    'KHR',
    'CNY',
    'EUR',
    'GEL',
    'INR',
    'IDR',
    'IRR',
    'IQD',
    'JPY',
    'JOD',
    'KZT',
    'KWD',
    'KGS',
    'LAK',
    'LBP',
    'MYR',
    'MVR',
    'MNT',
    'MMK',
    'NPR',
    'KPW',
    'OMR',
    'PKR',
    'ILS',
    'PHP',
    'QAR',
    'RUB',
    'SAR',
    'SGD',
    'KRW',
    'LKR',
    'SYP',
    'TWD',
    'TJS',
    'THB',
    'USD',
    'TRY',
    'TMT',
    'AED',
    'UZS',
    'VND',
    'AUD',
    'FJD',
    'AUD',
    'USD',
    'USD',
    'AUD',
    'NZD',
    'USD',
    'PGK',
    'WST',
    'SBD',
    'TOP',
    'AUD',
    'VUV'
  ];

  List<String> countries = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Greece",
    "Guernsey",
    "Hungary",
    "Iceland",
    "Ireland",
    "Isle of Man",
    "Italy",
    "Jersey",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Canada",
    "United States",
    "Mexico",
    "Greenland",
    "Cuba",
    "Dominican Republic",
    "Costa Rica",
    "Jamaica",
    "Panama",
    "Honduras",
    "Haiti",
    "El Salvador",
    "Nicaragua",
    "Bahamas",
    "Trinidad and Tobago",
    "Guatemala",
    "Barbados",
    "Saint Lucia",
    "Grenada",
    "Saint Vincent and the Grenadines",
    "Dominica",
    "Antigua and Barbuda",
    "Belize",
    "Saint Kitts and Nevis",
    "Saint Pierre and Miquelon",
    "Montserrat",
    "Turks and Caicos Islands",
    "British Virgin Islands",
    "Anguilla",
    "Cayman Islands",
    "Aruba",
    "Bermuda",
    "Puerto Rico",
    "United States Virgin Islands",
    "Sint Maarten",
    "Saint Martin",
    "Saint Barthélemy",
    "Bonaire",
    "Saba",
    "Sint Eustatius",
    "Clipperton Island",
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Cambodia',
    'China',
    'Cyprus',
    'Georgia',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'North Korea',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Sri Lanka',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'Turkey',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
    'Australia',
    'Fiji',
    'Kiribati',
    'Marshall Islands',
    'Micronesia',
    'Nauru',
    'New Zealand',
    'Palau',
    'Papua New Guinea',
    'Samoa',
    'Solomon Islands',
    'Tonga',
    'Tuvalu',
    'Vanuatu',
  ];

  var result = {};
  currencyConverter({
    have = 'USD',
    want = 'EGP',
    amount = 1,
  }) async {
    result = {};

    emit(LoadingCurrencyConverterState());

    var url = Uri.parse(
        'https://currency-converter-by-api-ninjas.p.rapidapi.com/v1/convertcurrency?have=$have&want=$want&amount=$amount');
    var headers = {
      'X-RapidAPI-Key': 'f806056228msh1b0793655feb2bfp13396ajsnb8b056de3ed4',
      'X-RapidAPI-Host': 'currency-converter-by-api-ninjas.p.rapidapi.com',
    };
    final response = await http.get(url, headers: headers);
    if (response.statusCode == 200) {
      result = jsonDecode(response.body);

      emit(SuccessCurrencyConverterState());
    } else {
      emit(ErrorCurrencyConverterState());
      throw Exception('Failed to fetch TV series');
    }
  }

  String firstSelectedItem = 'USD';
  String secondSelectedItem = 'EGP';
  changeFirstSelectedItem(newValue) {
    firstSelectedItem = newValue;
    emit(ChangeFirstSelectedItem());
  }

  changeSecondSelectedItem(newValue) {
    secondSelectedItem = newValue;
    emit(ChangeSecondSelectedItem());
  }
}
